name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Cambia esto a la versión que necesites

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'premejoraweb'  # Cambia esto por el nombre de tu App Service
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Secreto que configurarás más adelante
        package: ./
